app/urls.py
from . import views
from .views import *
from django.urls import path


urlpatterns = [
    path('' , views.home, name='home'),
    path('signout', views.signout, name='signout'),
    path('registerXlogin', views.registerXlogin, name='registerXlogin'),
    path('register', views.register, name='register'),
    path('login', views.login, name='login'),
    path('upload_profile_image/', upload_profile_image, name='upload_profile_image'),
    path('profile/', profile, name='profile'),
    path('profile/edit/', edit_profile, name='edit_profile'),
    path('admin1/', admin1, name='admin1'),
    path('management/', views.management, name='management'),
    path('user_management/', user_management_view, name='user_management'),
    path('products/', products, name='products'),
    path('product/<int:item_id>/', product, name='product'),
    path('productweb/product/<int:item_id>/', product, name='product'),
    path('contag/', contag, name='contag'),
    path('payments/', payments, name='payments'),
    path('add_product/', add_product, name='add_product'),
    path('delete_product_incart/<int:product_id>/', delete_product_incart, name='delete_product_incart'),
    path('add_cart/<int:id>/', add_cart, name='add_cart'),
    path('cart/',cart,name='cart'),
    path('order',order,name='order'),
    path('order2',order2,name='order2'),
    path('order3',order3,name='order3'),
    path('order4',order4,name='order4'),
    path('order5',order5,name='order5'),
    path('order6',order6,name='order6'),
    path('preorder/', views.preorder, name='preorder'),
    path('orders/', views.admin_order_list, name='admin_order_list'),
    path('orders/', views.admin_order_list, name='admin_order_list'),
    path('orders/update/<int:order_id>/', views.update_order_status, name='update_order_status'),
    path('orders/view/<int:order_id>/', views.view_order, name='view_order'),
    path('orders/track/<int:order_id>/', views.track_order, name='track_order'),
    path('delete_product/<int:product_id>/delete/', views.delete_product, name='delete_product'),
    path('chat', views.chat, name='chat'),
    path('chat_history/<int:receiver_id>/', views.chat_history, name='chat_history'),
    path('send_message/', views.send_message, name='send_message'),
    path('admin_chat_list', views.admin_chat_list, name='admin_chat'),
    path('admin_chat/<int:id>',views.admin_chat, name='delete_ScoreTopic'),
    path('messages/admin/<int:id>', views.admin_messages, name='latest_messages'),
    path('messages/customer/', views.customer_messages, name='latest_messages'),
    path('payment-tracking/', payment_tracking, name='payment_tracking'),
    path('create_payment/<int:id>', create_payment, name='create_payment'),
    path('send_payment/', send_payment, name='send_payment'),
    path('get_order_payment/<int:id>', get_order_payment, name='get_order_payment'),
    path('payment_slip/', views.payment_slip, name='payment_slip'),
    path('upload_payment_image/', views.upload_payment_image, name='upload_payment_image'),
    path('update_payment_status/', views.update_payment_status, name='update_payment_status'),
    path('delete_payment_image/<int:payment_id>/', views.delete_payment_image, name='delete_payment_image'),

    






]

webapp/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app/models.py
from django.db import models
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone

class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    profile_image = models.ImageField(upload_to='images_profile', null=True, blank=True)
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    email = models.EmailField()
    phone_number = models.CharField(max_length=15, null=True, blank=True)
    address = models.TextField(null=True, blank=True)
    birth_date = models.DateField(null=True, blank=True)
    pass1 = models.CharField(max_length=100, null=True, blank=True)

    def __str__(self):
        return self.user.username
    
class Item(models.Model):
    title = models.CharField(max_length=50)
    size = models.CharField(max_length=500)
    description = models.TextField(max_length=255, default='No description')
    material = models.CharField(max_length=50, default='No description')
    price = models.CharField(max_length=50)
    is_available = models.BooleanField(default=True, blank=True, null=True)

class ItemImage(models.Model):
    item = models.ForeignKey(Item, on_delete=models.CASCADE, related_name='images')
    image = models.ImageField(upload_to='product_images', null=True, blank=True)

class Cart(models.Model):
    cart = models.ForeignKey(UserProfile, on_delete=models.CASCADE)

class Detailcart(models.Model):
    itemImages = models.ForeignKey(ItemImage, on_delete=models.CASCADE)
    carts = models.ForeignKey(Cart, on_delete=models.CASCADE)
    amount = models.IntegerField()

class Order(models.Model):
    user_profile = models.ForeignKey(UserProfile, on_delete=models.CASCADE)
    name = models.CharField(max_length=100)
    category = models.CharField(max_length=50)  
    material = models.CharField(max_length=50)
    message = models.TextField()
    attachment = models.FileField(upload_to='order_attachments', null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    status = models.CharField(max_length=50, choices=[('รอดำเนินการ', 'รอดำเนินการ'), ('กำลังดำเนินการ', 'กำลังดำเนินการ'), ('ดำเนินการเสร็จสิ้น', 'ดำเนินการเสร็จสิ้น'), ('จัดส่งแล้ว', 'จัดส่งแล้ว'), ('จัดส่งเรียบร้อย', 'จัดส่งเรียบร้อย')])    

    def __str__(self):
        return f"Order {self.id}: {self.name} ({self.get_status_display()})"

class Message(models.Model):
    sender = models.ForeignKey(UserProfile, on_delete=models.CASCADE, related_name='sent_messages')
    receiver = models.ForeignKey(UserProfile, on_delete=models.CASCADE, related_name='received_messages')
    content = models.TextField()
    timestamp = models.DateTimeField(auto_now_add=True)

class Payment(models.Model):
    user = models.ForeignKey(UserProfile, on_delete=models.CASCADE)
    order = models.ForeignKey(Order, on_delete=models.CASCADE)
    image = models.ImageField(upload_to='payment_slips', null=True, blank=True)
    uploaded_at = models.DateTimeField(auto_now_add=True)
    is_verified = models.BooleanField(default=False)
    status = models.CharField(max_length=50, choices=[
        ('pending', 'รอตรวจสอบ'),
        ('verified', 'ชำระเงินเรียบร้อย'),
        ('rejected', 'การชำระเงินถูกปฏิเสธ')
    ], default='pending')
    price = models.DecimalField(max_digits=10, decimal_places=2)  # เพิ่มฟิลด์ราคา





    

app/templates/productweb/add_product.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Add Product</title>
    <link rel="stylesheet" href="{% static 'css/add.css' %}">
</head>
<body>
    {% include 'base/tab_login.html' %}
    {% include 'app/components/site_header.html' %}
    <div class="container">
        {% block content %}
            <h2>Add Product</h2>
            <form method="post" enctype="multipart/form-data">
                {% csrf_token %}
                {{ item_form.as_p }}
                {{ image_form.as_p }}
                <button type="submit">Add Product</button>
            </form>
        {% endblock %}
    </div>
</body>
</html>

app/templates/productweb/cart.html
{% load static %}
{% include 'base/tab_login.html' %}
{% include 'app/components/site_header.html' %}
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>ตะกร้าสินค้า</title>
    <link rel="stylesheet" href="{% static 'css/cart.css' %}">
</head>
<div class="cart-container">
    <script src="{% static 'js/cart1.js' %}"></script>
    <h2>ตะกร้าสินค้า</h2>
    <table class="cart-table">
        <thead>
            <tr>
                <th>สินค้า</th>
                <th>ราคา</th>
                <th>จำนวน</th>
                <th>เลือกที่จะสั่ง</th>
                <th>การจัดการ</th>
            </tr>
        </thead>
        <tbody>
            {% for item in cart %}
            <tr>
                <td>{{ item.itemImages.item.title }}</td>
                <td>{{ item.itemImages.item.price }}</td>
                <td>{{ item.amount }}</td>
                <td><input type="checkbox" name="selected_item" value="{{ item.id }}" onclick="limitCheckboxSelection(this)"></td>
                <td>
                    <form action="{% url 'delete_product_incart' item.id %}" method="post">
                        {% csrf_token %}
                        <button type="submit">ลบรายการ</button>
                    </form>
                </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
    <div class="cart-total">
        <a id="checkout-link" href="{% url 'order' %}" onclick="return limitCheckboxSelectionAndSubmit();"><button id="checkout-btn">สั่งซื้อ</button></a>
    </div>
    <script>
        function limitCheckboxSelectionAndSubmit() {
            var selectedItems = document.querySelectorAll('input[name="selected_item"]:checked');
    
            if (selectedItems.length === 1) {
                var selectedProductName = selectedItems[0].parentNode.parentNode.cells[0].innerText.trim();
                if (selectedProductName === "ป้ายกล่องไฟ") {
                    window.location.href = "{% url 'order2' %}";
                } else if (selectedProductName === "ป้ายสติ๊กเกอร์") {
                    window.location.href = "{% url 'order3' %}";
                } else if (selectedProductName === "ป้ายรีดฟิวเจอร์บอร์ด") {
                    window.location.href = "{% url 'order4' %}";
                } else if (selectedProductName === "ป้ายอักษรพลาสวูด") {
                    window.location.href = "{% url 'order5' %}";
                } else if (selectedProductName === "ป้ายรีดโฟมบอร์ด") {
                    window.location.href = "{% url 'order6' %}";
                } else {
                    window.location.href = "{% url 'order' %}";
                }
            } else {
                alert("Please select only one item to proceed with the order.");
            }
            return false; // Prevent default link action
        }
    </script>
</div>

app/templates/productweb/delete_product.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Delete Product</title>
    <link rel="stylesheet" href="{% static 'css/delete.css' %}">
</head>
<body>
    {% include 'base/tab_login.html' %}
    {% include 'app/components/site_header.html' %}
    <div class="container">
        {% block content %}
        <h2>Delete Product</h2>
        <p>Are you sure you want to delete '{{ product.title }}'?</p>
        <p class="product-size">Size: {{ product.size }}</p>
        <p class="product-matter">{{ product.material }}</p>
        <p class="product-description">{{ product.description }}</p>
        <p class="product-price">{{ product.price }}</p>
        <form method="post" id="delete-form">
            {% csrf_token %}
            <button type="submit" name="confirm_delete">Delete</button>
            <a href="{% url 'products' %}" class="cancel-link">Cancel</a>
        </form>
    {% endblock %}
    </div>
</body>
</html>

app/templates/productweb/get_order_payment.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Admin Panel</title>
    <link rel="stylesheet" href="{% static 'css/adminpage.css' %}">
</head>
<body>
    {% include 'base/tab_login.html' %}
    {% include 'app/components/site_header.html' %}

    <section>
        <h2>ส่งแจ้งการชำระ</h2>
    </section>
    <div>
        <div style="display: flex; justify-content: flex-end; align-items: flex-start;">
            <div style="flex: 1;">
                <form action="{% url 'payment_slip' %}" method="post" enctype="multipart/form-data" style="max-width: 600px; /* Adjust based on your layout */">
                    {% csrf_token %}
                    ชื่อป้ายที่ต้องการ <input type="text" name="name" value="{{order.order.name}}" readonly><br>
                    แบบป้าย <input type="text" name="get_material_display" value="{{order.order.get_material_display}}" readonly><br>
                    ขนาดป้าย <input type="text" name="get_category_display" value="{{order.order.get_category_display}}" readonly><br>
                    วัสดุ <input type="text" name="material" value="{{order.order.material}}" readonly><br>
                    ราคา <input type="text" name="price" value="{{order.order.price}}" readonly><br>
                    อีเมลล์ <input type="text" name="email" value="{{ order.order.user_profile.email }}" readonly><br>
                    อัปโหลดหลักฐาน<input type="file" name="file" id="">
                    <input type="text"  hidden name="order_id" value="{{ order.id }}" readonly><br>
                    <button type="submit">ส่งใบชำระเงิน</button>
                </form>
            </div>
            <div style="flex: 0 1 auto; margin-left: 20px; /* Adjust spacing as needed */">
                <img src="https://www.gsb.or.th/gsb-theme/images/Sharing_Default.jpg" alt="รูปภาพ" style="width: 100px; height: auto;">
                <p><strong>บัญชีธนาคาร:</strong> <span class="line-id">020005553350</span></p>
                <p><strong>หมายเหตุ:</strong> <span class="context">ราคาสินค้าท่านจะได้รับหลังจากช่างทำการผลิตป้ายตามสั่งเสร็จแล้ว</span></p>
            </div>
        </div>
    </div>
    
    

</body>
</html>

app/templates/productweb/order.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>สั่งซื้อป้าย</title>
<link rel="stylesheet" href="{% static 'css/order1.css' %}">
</head>
<body>
  {% include 'base/tab_login.html' %}
  {% include 'app/components/site_header.html' %}
<div class="container">
  <h2>ข้อมูลป้ายไวนิลที่จะสั่งทำ</h2>
  <form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    
    <label for="name">ชื่อป้ายไวนิลที่ต้องการ:</label>
    <input type="text" id="name" name="name" placeholder="ชื่อป้าย" required>

    <label for="category">ขนาดป้าย:</label>
    <select id="category" name="category">
      <option value="A0">ไวนิล (841 x 1189 มิลลิเมตร)</option>
      <option value="A1">ไวนิล (594 x 841 มิลลิเมตร)</option>
      <option value="A2">ไวนิล (420 x 594 มิลลิเมตร)</option>
      <option value="A3">ไวนิล (297 x 420 มิลลิเมตร)</option>
      <option value="A4">ไวนิล (210 x 297 มิลลิเมตร)</option>      
    </select>
    

    <label for="material">แบบป้าย:</label>
    <select id="material" name="material">
      <option value="Vinyl">ป้ายไวนิลธงญี่ปุ่น</option>
      <option value="Acrylic">ป้ายไวนิลโครงไม้/โครงเหล็ก</option>
      <option value="Metal">ป้ายกล่องไฟไวนิล</option>
      <option value="Wood">สติกเกอร์อิงค์เจ็ท</option>
      <option value="Foamboard">แคนวาสอิงค์เจ็ท</option>
    </select>    

    <label for="message">รายละเอียดป้ายเพิ่มเติม:</label>
    <textarea id="message" name="message" placeholder="เพิ่มเติมเกี่ยวกับป้าย"></textarea>

    <label for="attachment">Attachment:</label>
    <input type="file" id="attachment" name="attachment">

    <button type="submit">Order</button>
    
  </form>
</div>
<script src="{% static 'js/order1.js' %}"></script>
</body>
</html>

app/templates/productweb/order2.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>สั่งซื้อป้าย</title>
<link rel="stylesheet" href="{% static 'css/order1.css' %}">
</head>
<body>
  {% include 'base/tab_login.html' %}
  {% include 'app/components/site_header.html' %}
<div class="container">
  <h2>ข้อมูลป้ายไฟที่จะสั่งทำ</h2>
  <form method="post" enctype="multipart/form-data" id="form2" action="{% url 'order2' %}">
    {% csrf_token %}
    
    <label for="name">ชื่อป้ายไฟที่ต้องการ:</label>
    <input type="text" id="name" name="name" placeholder="ชื่อป้าย" required>

    <label for="category">ขนาดป้ายไฟ:</label>
    <select id="category" name="category">
      <option value="30x60">30 x 60 ซม.</option>
      <option value="40x80">40 x 80 ซม.</option>
      <option value="50x100">50 x 100 ซม.</option>
      <option value="60x120">60 x 120 ซม.</option>
      <option value="80x160">80 x 160 ซม.</option>
    </select>
    

    <label for="material">แบบป้าย:</label>
    <select id="material" name="material">
      <option value="Neon">ป้ายไฟนีออน</option>
      <option value="LED">ป้ายไฟ LED</option>
      <option value="Digital">ป้ายดิจิตอล</option>
    </select>
     
    
    <label for="material">วัสดุ:</label>
    <select id="material" name="material">
      <option value="Aluminum">อลูมิเนียม</option>
      <option value="Plastic">พลาสติก</option>
      <option value="Glass">แก้ว</option>
    </select>  

    <label for="message">รายละเอียดป้ายเพิ่มเติม:</label>
    <textarea id="message" name="message" placeholder="เพิ่มเติมเกี่ยวกับป้าย"></textarea>

    <label for="attachment">Attachment:</label>
    <input type="file" id="attachment" name="attachment">

    <button type="submit">Order</button>
    
  </form>
</div>
<script src="{% static 'js/order1.js' %}"></script>
</body>
</html>

app/templates/productweb/order3.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>สั่งซื้อป้าย</title>
<link rel="stylesheet" href="{% static 'css/order1.css' %}">
</head>
<body>
  {% include 'base/tab_login.html' %}
  {% include 'app/components/site_header.html' %}
<div class="container">
  
  <h2>ข้อมูลป้ายสติ๊กเกอร์ที่จะสั่งทำ</h2>
  <form method="post" enctype="multipart/form-data" id="form2" action="{% url 'order3' %}">
    {% csrf_token %}
    <label for="name">ชื่อป้ายสติ๊กเกอร์ที่ต้องการ:</label>
    <input type="text" id="name" name="name" placeholder="ชื่อป้าย">

    <label for="category">ขนาดป้าย:</label>
    <select id="category" name="category">
      <option value="15x40">15 x 40 ซม.</option>
      <option value="20x60">20 x 60 ซม.</option>
      <option value="30x80">30 x 80 ซม.</option>
    </select>

    <label for="material">วัสดุป้ายสติ๊กเกอร์:</label>
    <select id="material" name="material">
      <option value="Vinyl">วินิล</option>
      <option value="Paper">กระดาษ</option>
      <option value="Plastic">พลาสติก</option>
    </select>
    

    <label for="message">รายละเอียดป้ายเพิ่มเติม:</label>
    <textarea id="message" name="message" placeholder="Your message"></textarea>

    <label for="attachment">Attachment:</label>
    <input type="file" id="attachment" name="attachment">

    <button type="submit">Order</button>
    
  </form>
</div>

</body>
</html>

app/templates/productweb/order4.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>สั่งซื้อป้าย</title>
<link rel="stylesheet" href="{% static 'css/order1.css' %}">
</head>
<body>
  {% include 'base/tab_login.html' %}
  {% include 'app/components/site_header.html' %}
<div class="container">
  
  <h2>ข้อมูลป้ายรีดฟิวเจอร์บอร์ดที่จะสั่งทำ</h2>
  <form method="post" enctype="multipart/form-data" id="form2" action="{% url 'order4' %}">
    {% csrf_token %}
    <label for="name">ชื่อป้ายรีดฟิวเจอร์ที่ต้องการ:</label>
    <input type="text" id="name" name="name" placeholder="ชื่อป้าย">

    <label for="category">ขนาดป้าย:</label>
    <select id="category" name="category">
      <option value="15x40">15 x 40 ซม.</option>
      <option value="20x60">20 x 60 ซม.</option>
      <option value="30x80">30 x 80 ซม.</option>
      <option value="40x100">40 x 100 ซม.</option>
    </select>
    
    <label for="material">วัสดุป้าย:</label>
    <select id="material" name="material">
      <option value="Rigid_Foam_Board">กระดานโฟมแข็ง</option>
      <option value="Corrugated_Plastic">พลาสติกคอร์รูเกท</option>
      <option value="Aluminum">อลูมิเนียม</option>
      <option value="Acrylic">อะคริลิค</option>
    </select>

    <label for="message">รายละเอียดป้ายเพิ่มเติม:</label>
    <textarea id="message" name="message" placeholder="Your message"></textarea>

    <label for="attachment">Attachment:</label>
    <input type="file" id="attachment" name="attachment">

    <button type="submit">Order</button>
    
  </form>
</div>

</body>
</html>

app/templates/productweb/order5.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>สั่งซื้อป้าย</title>
<link rel="stylesheet" href="{% static 'css/order1.css' %}">
</head>
<body>
  {% include 'base/tab_login.html' %}
  {% include 'app/components/site_header.html' %}
<div class="container">
  
  <h2>ข้อมูลป้ายอักษรพลาสวูดที่จะสั่งทำ</h2>
  <form method="post" enctype="multipart/form-data" id="form2" action="{% url 'order5' %}">
    {% csrf_token %}
    <label for="name">ชื่อป้ายอักษรพลาสวูดที่ต้องการ:</label>
    <input type="text" id="name" name="name" placeholder="ชื่อป้าย">

    <label for="category">ขนาดป้าย:</label>
    <select id="category" name="category">
      <option value="15x30">15 x 30 ซม.</option>
      <option value="20x40">20 x 40 ซม.</option>
      <option value="25x50">25 x 50 ซม.</option>
      <option value="30x60">30 x 60 ซม.</option>
      <option value="35x70">35 x 70 ซม.</option>
    </select>
    
    <label for="material">วัสดุป้าย:</label>
    <select id="material" name="material">
      <option value="Acrylic">อะคริลิค</option>
      <option value="PVC">PVC</option>
      <option value="Polystyrene">โพลีสไตรีน</option>
      <option value="Polypropylene">โพลีโปรพิลีน</option>
      <option value="ABS">ABS</option>
    </select>
    

    <label for="message">รายละเอียดป้ายเพิ่มเติม:</label>
    <textarea id="message" name="message" placeholder="Your message"></textarea>

    <label for="attachment">Attachment:</label>
    <input type="file" id="attachment" name="attachment">

    <button type="submit">Order</button>
    
  </form>
</div>

</body>
</html>

app/templates/productweb/order6.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>สั่งซื้อป้าย</title>
<link rel="stylesheet" href="{% static 'css/order1.css' %}">
</head>
<body>
  {% include 'base/tab_login.html' %}
  {% include 'app/components/site_header.html' %}
<div class="container">
  
  <h2>ข้อมูลป้ายรีดโฟมบอร์ดที่จะสั่งทำ</h2>
  <form method="post" enctype="multipart/form-data" id="form2" action="{% url 'order6' %}">
    {% csrf_token %}
    <label for="name">ชื่อป้ายรีดโฟมบอร์ดที่ต้องการ:</label>
    <input type="text" id="name" name="name" placeholder="ชื่อป้าย">

    <label for="category">ขนาดป้าย:</label>
    <select id="category" name="category">
      <option value="15x40">15 x 40 ซม.</option>
      <option value="20x40">20 x 40 ซม.</option>
      <option value="25x50">25 x 50 ซม.</option>
      <option value="30x60">30 x 60 ซม.</option>
      <option value="35x70">35 x 70 ซม.</option>
    </select>
    
    <label for="material">วัสดุป้าย:</label>
    <select id="material" name="material">
      <option value="Rigid_Foam_Board">โฟมบอร์ดแข็ง</option>
    </select>
    

    <label for="message">รายละเอียดป้ายเพิ่มเติม:</label>
    <textarea id="message" name="message" placeholder="Your message"></textarea>

    <label for="attachment">Attachment:</label>
    <input type="file" id="attachment" name="attachment">

    <button type="submit">Order</button>
    
  </form>
</div>

</body>
</html>

app/templates/productweb/preorder.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<link rel="stylesheet" href="{% static 'css/preorder1.css' %}">
<title>รายการสั่งซื้อ</title>
</head>

<body>
  {% include 'base/tab_login.html' %}
  {% include 'app/components/site_header.html' %}
  <div class="container">
    <h1>รายการ Order</h1>
    {% for order in orders %}
    <div class="order-box">
      <div class="order-details">
        <div>
          <label>เลขคำสั่งซื้อ:</label> <a href="{% url 'track_order' order.id %}">{{ order.id }}</a>
        </div>
        <div>
          <label>เวลาสั่งซื้อ:</label> {{ order.created_at }}
        </div>
      </div>
      <div class="order-details">
        <div>
          <label>ชื่อผู้สั่ง:</label> {{ order.user_profile.user.first_name }} {{ order.user_profile.user.last_name }}
        </div>
        <div>
          <label>สถานะ:</label> {{ order.get_status_display }}
        </div>
      </div>
      <div class="order-details">
        <div>
          <label>ชื่อป้าย:</label> {{ order.name }}
        </div>
        <div>
          <label>ขนาด:</label> {{ order.get_category_display }}
        </div>
      </div>
      <div class="order-details">
        <div>
          <label>รายละเอียดเพิ่มเติม:</label>
          <div class="message-content">
            {{ order.message }}
          </div>
        </div>
      </div>
      <div class="order-details">
        <div>
          <label>ไฟล์งานเพิ่มเติม:</label>
          {% if order.attachment %}
          <a href="{{ order.attachment.url }}">ดาวน์โหลด</a>
          {% else %}
          N/A
          {% endif %}
        </div>
        <div>
          <a class="status-button" href="{% url 'track_order' order.id %}">ดูสถานะ</a>
        </div>
      </div>
    </div>
    {% endfor %}
  </div>
</body>
</html>

app/templates/productweb/product.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>ร้านบุญตา</title>
</head>
<body>

    {% include 'base/tab_login.html' %}
    {% include 'app/components/site_header.html' %}
    {% include 'tab/sidebar.html' %}
    <br>
    {% include 'productweb/products.html' %}
</body>
</html>